// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf1H_S4kk02GZNOKzuO4BfncnCbMvREW0',
    appId: '1:1054751758459:web:5495d7b2399ccfce1daade',
    messagingSenderId: '1054751758459',
    projectId: 'wina-app-7dc97',
    authDomain: 'wina-app-7dc97.firebaseapp.com',
    storageBucket: 'wina-app-7dc97.firebasestorage.app',
    measurementId: 'G-CXWMCE1MJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0IdOGrtb0akWTKJsDIj-CO8a_DKeGik',
    appId: '1:1054751758459:android:e93d02a8c21e56f01daade',
    messagingSenderId: '1054751758459',
    projectId: 'wina-app-7dc97',
    storageBucket: 'wina-app-7dc97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4UK0eMkHIIFvNHL3YFPYJPLUbfQlciE',
    appId: '1:1054751758459:ios:00dff1dbe3371c201daade',
    messagingSenderId: '1054751758459',
    projectId: 'wina-app-7dc97',
    storageBucket: 'wina-app-7dc97.firebasestorage.app',
    iosBundleId: 'com.example.wina',
  );
}
