# ios/Podfile
platform :ios, '15.0'

use_frameworks!
use_modular_headers!

# Ignore all warnings from all pods
inhibit_all_warnings!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../.flutter'
  eval(File.read(File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')), binding)

  flutter_ios_podfile_setup

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
